# Cpp language
language: cpp
sudo: required
dist: trusty

# Compiler selection
compiler:
  - clang
  - gcc
# Enable caching
cache:
  apt: true
# Build matrix
addons:
  apt:
    sources: 
        - george-edison55-precise-backports
        - ubuntu-toolchain-r-test
        - llvm-toolchain-precise-3.8
    packages:
        - clang-3.8
        - g++-5
        - gcc-5
        - cmake
        - cmake-data
        - libpthread-stubs0-dev
        - libgl1-mesa-dev
        - xorg-dev
# Install
install:
  - if [ "$TRAVIS_OS_NAME" = "linux" -a "$CXX" = "g++" ]; then export CXX="g++-5" CC="gcc-5"; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" -a "$CXX" = "clang++" ]; then export CXX="clang++-3.8" CC="clang-3.8"; fi

# Build steps
script:
  - mkdir build
  - cd build
  - cmake .. && make